
project_id = "vnccezzqcohvgzkwojqz"

[functions.create-manual-order]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.scan-ticket]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
